#!/bin/bash

ciphersuite="ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"

#Install Stretch's repo config
cat > stretch.list <<EOF
deb http://ftp.fr.debian.org/debian stretch main contrib non-free
deb http://security.debian.org/ stretch/updates main contrib non-free
EOF
sudo chown root:root stretch.list
sudo mv stretch.list /etc/apt/sources.list.d/

#Update nginx and openssl
sudo apt-get update -qq
sudo apt-get -y -t stretch install nginx-extras openssl

#Get all the domains
domains=$(sudo yunohost domain list | grep - | awk -F' ' '{print $2}')

#Update config files of all the domains
for domain in $domain; do
  sudo sed -e 's/ssl;/ssl http2;/' /etc/nginx/conf.d/$domain.conf;
  sudo sed -e 's/ssl_ciphers .*$/ssl_ciphers $ciphersuite;/';
done;

#Restart nginx
sudo service nginx restart
