#!/bin/bash

ciphersuite="ECDHE-RSA-AES128-GCM-SHA256:ECDHE-ECDSA-AES128-GCM-SHA256:ECDHE-RSA-AES256-GCM-SHA384:ECDHE-ECDSA-AES256-GCM-SHA384:DHE-RSA-AES128-GCM-SHA256:DHE-DSS-AES128-GCM-SHA256:kEDH+AESGCM:ECDHE-RSA-AES128-SHA256:ECDHE-ECDSA-AES128-SHA256:ECDHE-RSA-AES128-SHA:ECDHE-ECDSA-AES128-SHA:ECDHE-RSA-AES256-SHA384:ECDHE-ECDSA-AES256-SHA384:ECDHE-RSA-AES256-SHA:ECDHE-ECDSA-AES256-SHA:DHE-RSA-AES128-SHA256:DHE-RSA-AES128-SHA:DHE-DSS-AES128-SHA256:DHE-RSA-AES256-SHA256:DHE-DSS-AES256-SHA:DHE-RSA-AES256-SHA:ECDHE-RSA-DES-CBC3-SHA:ECDHE-ECDSA-DES-CBC3-SHA:AES128-GCM-SHA256:AES256-GCM-SHA384:AES128-SHA256:AES256-SHA256:AES128-SHA:AES256-SHA:AES:CAMELLIA:DES-CBC3-SHA:!aNULL:!eNULL:!EXPORT:!DES:!RC4:!MD5:!PSK:!aECDH:!EDH-DSS-DES-CBC3-SHA:!EDH-RSA-DES-CBC3-SHA:!KRB5-DES-CBC3-SHA"

#Install repos config
echo -e "deb http://ftp.fr.debian.org/debian stretch main contrib non-free\n\
deb http://security.debian.org/ stretch/updates main contrib non-free\n\
deb http://ftp.debian.org/debian jessie-backports main" > http2.list
sudo chown root:root http2.list
sudo mv http2.list /etc/apt/sources.list.d/

#Install apt preferences
echo -e "Package: openssl\n\
Pin: release n=stretch\n\
Pin-Priority: 990\n\

Package: nginx*\n\
Pin: release a=jessie-backports\n\
Pin-Priority: 990" > http2
sudo chown root:root http2
sudo mv http2 /etc/apt/preferences.d/

#Update nginx and openssl
sudo apt-get update -qq
sudo apt-get -qq -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" -y- t jessie-backports install nginx-extras
sudo apt-get -qq -y -t stretch install openssl

#Get all the domains
domains=$(sudo yunohost domain list | grep - | awk -F' ' '{print $2}')

#Update config template file
sudo sed -i 's/ssl;/ssl http2;/' /usr/share/yunohost/yunohost-config/nginx/template.conf;
sudo sed -i "s/ssl_ciphers .*$/ssl_ciphers $ciphersuite;/" /usr/share/yunohost/yunohost-config/nginx/template.conf;

#Update config files of all the domains
for domain in $domains; do
  sudo sed -i 's/ssl;/ssl http2;/' /etc/nginx/conf.d/$domain.conf;
  sudo sed -i "s/ssl_ciphers .*$/ssl_ciphers $ciphersuite;/" /etc/nginx/conf.d/$domain.conf;
done;

#Restart nginx
sudo service nginx restart
